### ISSUE TITLE
У МЕНЯ НЕ КЕКАЕТ ОБЕД

### ISSUE THREAD

**Issue by tailsjs** [KitenokGene/ObedOS#1]
Я ПЫТАЛСЯ ВОЛШЕБНО КЕКНУТЬ ОБЕД НО УЮТНЕНЬКО НЕ ПОЗВОЛЯЕТ!!!

**Comment by KitenokGene** [comment]
ПОПРОСИТЕ ДОСТУП У КОФЕ

**Comment by tailsjs** [comment]
ЗДРАВСТВУЙТЕ Я ПОПРОСИЛ ДОСТУП У КОФЕ НО ОН КЕКНУЛ ЧТО ОБЕД НЕ ПРИНИМАЕТ ВОЛШЕБНЫЙ УЮТНЕНЬКО

**Comment by KitenokGene** [comment]
ЗДРАВСТВУЙТЕ, ХЗ
